# Generated by Django 2.2 on 2020-07-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Ypsilanti', max_length=50),
        ),
    ]
