# Generated by Django 2.2 on 2020-06-14 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200614_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='label',
        ),
    ]
