# Generated by Django 2.2 on 2020-06-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_vendor_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vendor_id',
            field=models.FloatField(default='0'),
            preserve_default=False,
        ),
    ]
