# Generated by Django 2.2 on 2020-06-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200615_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='owner',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
