# Generated by Django 2.2 on 2020-06-18 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile'),
        ),
    ]
