# Generated by Django 2.2 on 2020-06-18 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_item_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='core.Vendor'),
            preserve_default=False,
        ),
    ]
