# Generated by Django 2.2 on 2020-06-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_item_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
    ]
