# Generated by Django 2.2 on 2020-06-25 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_userprofile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
    ]
