# Generated by Django 2.2 on 2020-06-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_userprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='links',
            field=models.ManyToManyField(blank=True, to='core.PostLink'),
        ),
    ]
