# Generated by Django 2.2 on 2020-06-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200625_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vendor_owner',
            field=models.BooleanField(default=False),
        ),
    ]
