# Generated by Django 2.2 on 2020-07-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200629_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='zip_code',
            field=models.IntegerField(default=48197),
            preserve_default=False,
        ),
    ]
