# Generated by Django 2.2 on 2020-07-03 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_vendor_zip_code'),
        ('core', '0035_auto_20200630_2320'),
    ]

    operations = [
    ]
