# Generated by Django 2.2 on 2020-07-08 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20200707_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='received',
            new_name='delivered',
        ),
    ]
