# Generated by Django 2.2 on 2020-07-10 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20200707_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='address',
            name='default',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='addresses',
            field=models.ManyToManyField(to='core.Address'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='address', to='core.Address'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vendor',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
