# Generated by Django 2.2 on 2020-07-10 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_vendor_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_start', models.TimeField()),
                ('monday_end', models.TimeField()),
                ('tuesday_start', models.TimeField()),
                ('tuesday_end', models.TimeField()),
                ('wednesday_start', models.TimeField()),
                ('wednesday_end', models.TimeField()),
                ('thursday_start', models.TimeField()),
                ('thursday_end', models.TimeField()),
                ('friday_start', models.TimeField()),
                ('friday_end', models.TimeField()),
                ('sunday_start', models.TimeField()),
                ('sunday_end', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='vendor',
            name='hours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hours', to='core.VendorHours'),
        ),
    ]
