# Generated by Django 2.2 on 2020-07-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20200710_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorhours',
            name='saturday_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='vendorhours',
            name='saturday_start',
            field=models.TimeField(null=True),
        ),
    ]
