# Generated by Django 2.2 on 2020-07-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20200710_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(to='core.Vendor'),
        ),
    ]
