# Generated by Django 2.2 on 2020-07-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
    ]
