# Generated by Django 2.2 on 2020-07-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_postcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='addresses',
            field=models.ManyToManyField(blank=True, to='core.Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, to='core.Vendor'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, to='core.Post'),
        ),
    ]
