# Generated by Django 2.2 on 2020-07-16 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_order_authorized'),
        ('core', '0060_auto_20200715_1402'),
    ]

    operations = [
    ]
