# Generated by Django 2.2 on 2020-07-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_order_vendor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptiveTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='GeneralTag',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
