# Generated by Django 2.2 on 2020-07-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20200717_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
