# Generated by Django 2.2 on 2020-07-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20200720_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='zip_code',
            field=models.CharField(default=48197, max_length=100),
            preserve_default=False,
        ),
    ]
