# Generated by Django 2.2 on 2020-07-27 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_vendor_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Ypsilanti', max_length=50),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_vendor', to='core.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='StorePromotion',
            fields=[
                ('promotion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Promotion')),
                ('products', models.ManyToManyField(to='core.Item')),
            ],
            bases=('core.promotion',),
        ),
        migrations.CreateModel(
            name='ProductPromotion',
            fields=[
                ('promotion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Promotion')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_product', to='core.Item')),
            ],
            bases=('core.promotion',),
        ),
        migrations.CreateModel(
            name='PostPromotion',
            fields=[
                ('promotion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Promotion')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_post', to='core.Post')),
            ],
            bases=('core.promotion',),
        ),
    ]
