# Generated by Django 2.2 on 2020-07-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_vendor_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Ypsilanti', max_length=50),
        ),
    ]
