# Generated by Django 2.2 on 2020-07-21 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_vendor_zip_code'),
        ('core', "'0070_auto_20200720_1934"),
    ]

    operations = [
    ]
