# Generated by Django 2.2 on 2020-08-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_postpromotion_productpromotion_storepromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='denied',
            field=models.BooleanField(default=False),
        ),
    ]
