# Generated by Django 2.2 on 2020-08-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_order_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
